#!/usr/bin/env python3
"""
Regenerate src/lib/data/{treatmentModel,riskModel}.coefficients.json from the
original fit outputs, instead of hand-transcribing numbers into TypeScript.

STATUS: this script is a documented template, not something that has been run
end-to-end in this repo. Neither original artifact is checked in:
  - the treatment model's ArviZ summary (an `az.summary(idata)` pandas
    DataFrame, saved as CSV/Parquet)
  - the risk model's `orm_fit.rds` (an `orm` object from R's `rms` package)
The two JSON files currently in src/lib/data/ were populated directly from
values supplied in chat and cross-checked numerically (e.g. the risk model's
per-category probabilities sum to 1, the point estimate moves sensibly with
severity — see the regression tests in test/). Treat this script as the
intended long-term path once the real artifacts are available, not as proof
those JSON files are correct.

Usage (once you have the real artifacts):
    pip install rdata pandas   # rdata: pure-Python .rds reader, no R needed
    python scripts/export-model-coefficients.py treatment az_summary.csv
    python scripts/export-model-coefficients.py risk orm_fit.rds

Each subcommand overwrites the corresponding JSON file in src/lib/data/.
Re-run this after every re-fit instead of editing the JSON (or the .ts model
files) by hand — that's the whole point of splitting data out of code.
"""

import argparse
import json
import sys
from pathlib import Path

DATA_DIR = Path(__file__).resolve().parent.parent / "src" / "lib" / "data"


def export_treatment_model(az_summary_csv: Path) -> dict:
    """
    Build treatmentModel.coefficients.json from an ArviZ summary table
    (the output of `az.summary(idata).to_csv(...)` on the fitted Bayesian IPD
    meta-analysis model), indexed by parameter name with "mean", "hdi_3%" and
    "hdi_97%" columns (ArviZ's default 94% HDI — re-run az.summary(idata,
    hdi_prob=0.95) for a true 95% interval matching this app's "95% credible
    interval" copy).

    Expected row index (parameter names) — adjust to match your model's
    actual naming if it differs:
      alpha_study[<trial_id>]  (one row per trial)
      beta_component[follow_up_2_4_weeks]
      beta_component[relapse_prevention_plan]
      beta_component_interaction
      gamma_phq9
      theta_age
      theta_sex
      delta_c1_age, delta_c2_age, delta_c1_sex, delta_c2_sex
      sigma
    Plus the standardization constants (mean/sd of age and baseline_phq9 in
    the training data) and the sex coding, which az.summary() does not know
    about — pass those in separately if this function is adapted for reuse.
    """
    import pandas as pd

    summary = pd.read_csv(az_summary_csv, index_col=0)

    def coef_ci(param: str) -> dict:
        row = summary.loc[param]
        hdi_lo = row.get("hdi_3%", row.get("hdi_2.5%"))
        hdi_hi = row.get("hdi_97%", row.get("hdi_97.5%"))
        return {"estimate": float(row["mean"]), "ci": [float(hdi_lo), float(hdi_hi)]}

    alpha_rows = [i for i in summary.index if str(i).startswith("alpha_study[")]
    alpha_study_by_trial = {
        str(i).removeprefix("alpha_study[").removesuffix("]"): float(summary.loc[i, "mean"])
        for i in alpha_rows
    }

    return {
        "sourceNote": (
            "Bayesian IPD (individual patient data) meta-analysis model — "
            "posterior means and 95% credible intervals (HDI) from "
            "az.summary(). See src/lib/model.ts for the full linear-"
            "predictor equation, sign-convention reasoning, and caveats. "
            "Regenerated by scripts/export-model-coefficients.py — do not "
            "hand-edit."
        ),
        "modelVersion": "0.5-fitted",
        "alphaStudyByTrial": alpha_study_by_trial,
        "coefficients": {
            "betaFollowUp": coef_ci("beta_component[follow_up_2_4_weeks]"),
            "betaRelapse": coef_ci("beta_component[relapse_prevention_plan]"),
            "betaInteraction": coef_ci("beta_component_interaction"),
            "gammaPhq9": coef_ci("gamma_phq9"),
            "thetaAge": coef_ci("theta_age"),
            "thetaSex": coef_ci("theta_sex"),
            "deltaC1Age": coef_ci("delta_c1_age"),
            "deltaC2Age": coef_ci("delta_c2_age"),
            "deltaC1Sex": coef_ci("delta_c1_sex"),
            "deltaC2Sex": coef_ci("delta_c2_sex"),
            "sigma": float(summary.loc["sigma", "mean"]),
        },
        # NOTE: az.summary() has no notion of these — carry them forward from
        # the existing JSON (or the training-data script) rather than
        # inventing new ones here.
        "standardization": json.loads(
            (DATA_DIR / "treatmentModel.coefficients.json").read_text()
        )["standardization"],
        "sexCode": {"male": 0, "female": 1},
    }


def export_risk_model(rds_path: Path) -> dict:
    """
    Build riskModel.coefficients.json from orm_fit.rds (an `orm` object from
    R's `rms` package), parsed with the pure-Python `rdata` package — no R
    runtime required. Field names below match what `rdata.read_rds()`
    produces for an `orm` object's `coefficients` (a named vector) and
    `Design$parms` (the knot locations used by each rcs() term).
    """
    import rdata

    parsed = rdata.read_rds(rds_path)
    coefficients = dict(parsed["coefficients"])
    parms = parsed["Design"]["parms"]

    def slope(name: str) -> float:
        return float(coefficients[name])

    intercepts = [float(coefficients[f"y>={j}"]) for j in range(1, 21)]

    return {
        "sourceNote": (
            "rms::orm proportional-odds ordinal regression (orm_fit.rds) "
            "predicting phq9_12mo from age, sex, baseline_phq9 and "
            "gad7_total — each numeric predictor as a 4-knot restricted "
            "cubic spline. See src/lib/riskModel.ts for the full equation "
            "and caveats. Regenerated by "
            "scripts/export-model-coefficients.py — do not hand-edit."
        ),
        "knots": {
            "age": [float(k) for k in parms["age"]],
            "baselinePhq9": [float(k) for k in parms["baseline_phq9"]],
            "gad7": [float(k) for k in parms["gad7_total"]],
        },
        "slopes": {
            "age": slope("age"),
            "ageP": slope("age'"),
            "agePP": slope("age''"),
            "sexMale": slope("sex=Male"),
            "baselinePhq9": slope("baseline_phq9"),
            "baselinePhq9P": slope("baseline_phq9'"),
            "baselinePhq9PP": slope("baseline_phq9''"),
            "gad7": slope("gad7_total"),
            "gad7P": slope("gad7_total'"),
            "gad7PP": slope("gad7_total''"),
        },
        "intercepts": intercepts,
    }


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("model", choices=["treatment", "risk"])
    parser.add_argument("source", type=Path, help="az_summary.csv or orm_fit.rds")
    args = parser.parse_args()

    if args.model == "treatment":
        data = export_treatment_model(args.source)
        out_path = DATA_DIR / "treatmentModel.coefficients.json"
    else:
        data = export_risk_model(args.source)
        out_path = DATA_DIR / "riskModel.coefficients.json"

    out_path.write_text(json.dumps(data, indent=2, ensure_ascii=False) + "\n")
    print(f"Wrote {out_path}", file=sys.stderr)


if __name__ == "__main__":
    main()
