/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AngeboteRouteImport } from './routes/angebote'
import { Route as ErgebnisRouteImport } from './routes/ergebnis'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as FragebogenRouteImport } from './routes/fragebogen'
import { Route as MethodologyRouteImport } from './routes/methodology'
import { Route as PraxisRouteImport } from './routes/praxis'
import { Route as SoforthilfeRouteImport } from './routes/soforthilfe'
import { Route as WartenRouteImport } from './routes/warten'
import { Route as WartezimmerRouteImport } from './routes/wartezimmer'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AngeboteRoute = AngeboteRouteImport.update({
  id: '/angebote',
  path: '/angebote',
  getParentRoute: () => rootRouteImport,
} as any)
const ErgebnisRoute = ErgebnisRouteImport.update({
  id: '/ergebnis',
  path: '/ergebnis',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const FragebogenRoute = FragebogenRouteImport.update({
  id: '/fragebogen',
  path: '/fragebogen',
  getParentRoute: () => rootRouteImport,
} as any)
const MethodologyRoute = MethodologyRouteImport.update({
  id: '/methodology',
  path: '/methodology',
  getParentRoute: () => rootRouteImport,
} as any)
const PraxisRoute = PraxisRouteImport.update({
  id: '/praxis',
  path: '/praxis',
  getParentRoute: () => rootRouteImport,
} as any)
const SoforthilfeRoute = SoforthilfeRouteImport.update({
  id: '/soforthilfe',
  path: '/soforthilfe',
  getParentRoute: () => rootRouteImport,
} as any)
const WartenRoute = WartenRouteImport.update({
  id: '/warten',
  path: '/warten',
  getParentRoute: () => rootRouteImport,
} as any)
const WartezimmerRoute = WartezimmerRouteImport.update({
  id: '/wartezimmer',
  path: '/wartezimmer',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/angebote': typeof AngeboteRoute
  '/ergebnis': typeof ErgebnisRoute
  '/faq': typeof FaqRoute
  '/fragebogen': typeof FragebogenRoute
  '/methodology': typeof MethodologyRoute
  '/praxis': typeof PraxisRoute
  '/soforthilfe': typeof SoforthilfeRoute
  '/warten': typeof WartenRoute
  '/wartezimmer': typeof WartezimmerRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/angebote': typeof AngeboteRoute
  '/ergebnis': typeof ErgebnisRoute
  '/faq': typeof FaqRoute
  '/fragebogen': typeof FragebogenRoute
  '/methodology': typeof MethodologyRoute
  '/praxis': typeof PraxisRoute
  '/soforthilfe': typeof SoforthilfeRoute
  '/warten': typeof WartenRoute
  '/wartezimmer': typeof WartezimmerRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/angebote': typeof AngeboteRoute
  '/ergebnis': typeof ErgebnisRoute
  '/faq': typeof FaqRoute
  '/fragebogen': typeof FragebogenRoute
  '/methodology': typeof MethodologyRoute
  '/praxis': typeof PraxisRoute
  '/soforthilfe': typeof SoforthilfeRoute
  '/warten': typeof WartenRoute
  '/wartezimmer': typeof WartezimmerRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/angebote'
    | '/ergebnis'
    | '/faq'
    | '/fragebogen'
    | '/methodology'
    | '/praxis'
    | '/soforthilfe'
    | '/warten'
    | '/wartezimmer'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/angebote'
    | '/ergebnis'
    | '/faq'
    | '/fragebogen'
    | '/methodology'
    | '/praxis'
    | '/soforthilfe'
    | '/warten'
    | '/wartezimmer'
  id:
    | '__root__'
    | '/'
    | '/angebote'
    | '/ergebnis'
    | '/faq'
    | '/fragebogen'
    | '/methodology'
    | '/praxis'
    | '/soforthilfe'
    | '/warten'
    | '/wartezimmer'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AngeboteRoute: typeof AngeboteRoute
  ErgebnisRoute: typeof ErgebnisRoute
  FaqRoute: typeof FaqRoute
  FragebogenRoute: typeof FragebogenRoute
  MethodologyRoute: typeof MethodologyRoute
  PraxisRoute: typeof PraxisRoute
  SoforthilfeRoute: typeof SoforthilfeRoute
  WartenRoute: typeof WartenRoute
  WartezimmerRoute: typeof WartezimmerRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/angebote': {
      id: '/angebote'
      path: '/angebote'
      fullPath: '/angebote'
      preLoaderRoute: typeof AngeboteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ergebnis': {
      id: '/ergebnis'
      path: '/ergebnis'
      fullPath: '/ergebnis'
      preLoaderRoute: typeof ErgebnisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fragebogen': {
      id: '/fragebogen'
      path: '/fragebogen'
      fullPath: '/fragebogen'
      preLoaderRoute: typeof FragebogenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/methodology': {
      id: '/methodology'
      path: '/methodology'
      fullPath: '/methodology'
      preLoaderRoute: typeof MethodologyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/praxis': {
      id: '/praxis'
      path: '/praxis'
      fullPath: '/praxis'
      preLoaderRoute: typeof PraxisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/soforthilfe': {
      id: '/soforthilfe'
      path: '/soforthilfe'
      fullPath: '/soforthilfe'
      preLoaderRoute: typeof SoforthilfeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/warten': {
      id: '/warten'
      path: '/warten'
      fullPath: '/warten'
      preLoaderRoute: typeof WartenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wartezimmer': {
      id: '/wartezimmer'
      path: '/wartezimmer'
      fullPath: '/wartezimmer'
      preLoaderRoute: typeof WartezimmerRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AngeboteRoute: AngeboteRoute,
  ErgebnisRoute: ErgebnisRoute,
  FaqRoute: FaqRoute,
  FragebogenRoute: FragebogenRoute,
  MethodologyRoute: MethodologyRoute,
  PraxisRoute: PraxisRoute,
  SoforthilfeRoute: SoforthilfeRoute,
  WartenRoute: WartenRoute,
  WartezimmerRoute: WartezimmerRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
