/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as AnmeldenRouteImport } from './routes/anmelden'
import { Route as SoforthilfeRouteImport } from './routes/soforthilfe'
import { Route as AuthenticatedAngeboteRouteImport } from './routes/_authenticated.angebote'
import { Route as AuthenticatedErgebnisRouteImport } from './routes/_authenticated.ergebnis'
import { Route as AuthenticatedFragebogenRouteImport } from './routes/_authenticated.fragebogen'
import { Route as AuthenticatedPraxisRouteImport } from './routes/_authenticated.praxis'
import { Route as AuthenticatedPatientPatientIdRouteImport } from './routes/_authenticated.patient.$patientId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AnmeldenRoute = AnmeldenRouteImport.update({
  id: '/anmelden',
  path: '/anmelden',
  getParentRoute: () => rootRouteImport,
} as any)
const SoforthilfeRoute = SoforthilfeRouteImport.update({
  id: '/soforthilfe',
  path: '/soforthilfe',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAngeboteRoute = AuthenticatedAngeboteRouteImport.update({
  id: '/angebote',
  path: '/angebote',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedErgebnisRoute = AuthenticatedErgebnisRouteImport.update({
  id: '/ergebnis',
  path: '/ergebnis',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedFragebogenRoute = AuthenticatedFragebogenRouteImport.update({
  id: '/fragebogen',
  path: '/fragebogen',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedPraxisRoute = AuthenticatedPraxisRouteImport.update({
  id: '/praxis',
  path: '/praxis',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedPatientPatientIdRoute =
  AuthenticatedPatientPatientIdRouteImport.update({
    id: '/patient/$patientId',
    path: '/patient/$patientId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/anmelden': typeof AnmeldenRoute
  '/soforthilfe': typeof SoforthilfeRoute
  '/angebote': typeof AuthenticatedAngeboteRoute
  '/ergebnis': typeof AuthenticatedErgebnisRoute
  '/fragebogen': typeof AuthenticatedFragebogenRoute
  '/praxis': typeof AuthenticatedPraxisRoute
  '/patient/$patientId': typeof AuthenticatedPatientPatientIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/anmelden': typeof AnmeldenRoute
  '/soforthilfe': typeof SoforthilfeRoute
  '/angebote': typeof AuthenticatedAngeboteRoute
  '/ergebnis': typeof AuthenticatedErgebnisRoute
  '/fragebogen': typeof AuthenticatedFragebogenRoute
  '/praxis': typeof AuthenticatedPraxisRoute
  '/patient/$patientId': typeof AuthenticatedPatientPatientIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/anmelden': typeof AnmeldenRoute
  '/soforthilfe': typeof SoforthilfeRoute
  '/_authenticated/angebote': typeof AuthenticatedAngeboteRoute
  '/_authenticated/ergebnis': typeof AuthenticatedErgebnisRoute
  '/_authenticated/fragebogen': typeof AuthenticatedFragebogenRoute
  '/_authenticated/praxis': typeof AuthenticatedPraxisRoute
  '/_authenticated/patient/$patientId': typeof AuthenticatedPatientPatientIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/anmelden'
    | '/soforthilfe'
    | '/angebote'
    | '/ergebnis'
    | '/fragebogen'
    | '/praxis'
    | '/patient/$patientId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/anmelden'
    | '/soforthilfe'
    | '/angebote'
    | '/ergebnis'
    | '/fragebogen'
    | '/praxis'
    | '/patient/$patientId'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/anmelden'
    | '/soforthilfe'
    | '/_authenticated/angebote'
    | '/_authenticated/ergebnis'
    | '/_authenticated/fragebogen'
    | '/_authenticated/praxis'
    | '/_authenticated/patient/$patientId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  AnmeldenRoute: typeof AnmeldenRoute
  SoforthilfeRoute: typeof SoforthilfeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/anmelden': {
      id: '/anmelden'
      path: '/anmelden'
      fullPath: '/anmelden'
      preLoaderRoute: typeof AnmeldenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/soforthilfe': {
      id: '/soforthilfe'
      path: '/soforthilfe'
      fullPath: '/soforthilfe'
      preLoaderRoute: typeof SoforthilfeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/angebote': {
      id: '/_authenticated/angebote'
      path: '/angebote'
      fullPath: '/angebote'
      preLoaderRoute: typeof AuthenticatedAngeboteRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/ergebnis': {
      id: '/_authenticated/ergebnis'
      path: '/ergebnis'
      fullPath: '/ergebnis'
      preLoaderRoute: typeof AuthenticatedErgebnisRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/fragebogen': {
      id: '/_authenticated/fragebogen'
      path: '/fragebogen'
      fullPath: '/fragebogen'
      preLoaderRoute: typeof AuthenticatedFragebogenRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/praxis': {
      id: '/_authenticated/praxis'
      path: '/praxis'
      fullPath: '/praxis'
      preLoaderRoute: typeof AuthenticatedPraxisRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/patient/$patientId': {
      id: '/_authenticated/patient/$patientId'
      path: '/patient/$patientId'
      fullPath: '/patient/$patientId'
      preLoaderRoute: typeof AuthenticatedPatientPatientIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedAngeboteRoute: typeof AuthenticatedAngeboteRoute
  AuthenticatedErgebnisRoute: typeof AuthenticatedErgebnisRoute
  AuthenticatedFragebogenRoute: typeof AuthenticatedFragebogenRoute
  AuthenticatedPraxisRoute: typeof AuthenticatedPraxisRoute
  AuthenticatedPatientPatientIdRoute: typeof AuthenticatedPatientPatientIdRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAngeboteRoute: AuthenticatedAngeboteRoute,
  AuthenticatedErgebnisRoute: AuthenticatedErgebnisRoute,
  AuthenticatedFragebogenRoute: AuthenticatedFragebogenRoute,
  AuthenticatedPraxisRoute: AuthenticatedPraxisRoute,
  AuthenticatedPatientPatientIdRoute: AuthenticatedPatientPatientIdRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  AnmeldenRoute: AnmeldenRoute,
  SoforthilfeRoute: SoforthilfeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
